<?php

namespace PhalconRest\Mvc;

use Phalcon\Mvc\ModelInterface;

class Model extends \Phalcon\Mvc\Model
{
    public function assign(array $data, $whiteList = null, $dataColumnMap = null): ModelInterface
    {
        return parent::assign($data, $whiteList ?? $this->whitelist(), $dataColumnMap); // TODO: Change the autogenerated stub
    }

    public function whitelist()
    {
        return null;
    }
}
